# Generated by Django 3.1.7 on 2021-04-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210407_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completedTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
